<?php
define("BASEBODY" , [
    0 => "銅",
    1 => "金",
    2 => "綠",
    3 => "紫",
    4 => "豹紋",
    5 => "迷彩",
    6 => "紅",
    7 => "銀",
    8 => "黃",
    9 => "黑",
    10 => "藍"
]);

define("HEAD" , [
    0 => "",
    1 => "肌肉",
    2 => "狼形",
    3 => "武士",
    4 => "狂鯊",
    5 => "電子",
    6 => "鉚釘",
    7 => "鬥兔",
    8 => "阿杜",
    9 => "杰倫",
    10 => "耕宏",
    11 => "天線",
    12 => "牛角",
    13 => "青蛙",
    14 => "",
    15 => "",
    16 => "小釘",
    17 => "小刺",
    18 => "小鯊",
    19 => ""
]);

define("SHOULDER", [
    0 => "",
    1 => "肌肉",
    2 => "狼形",
    3 => "武士",
    4 => "狂鯊",
    5 => "電子",
    6 => "鉚釘",
    7 => "鬥兔",
    8 => "阿杜",
    9 => "杰倫",
    10 => "耕宏",
    11 => "天線",
    12 => "牛角",
    13 => "青蛙",
    14 => "圓球",
    15 => "三角",
    16 => "",
    17 => "小刺",
    18 => "",
    19 => "鯊肩"
]);

define("ARMS", [
    0 => "",
    1 => "肌肉",
    2 => "狼形",
    3 => "武士",
    4 => "狂鯊",
    5 => "電子",
    6 => "鉚釘",
    7 => "鬥兔",
    8 => "阿杜",
    9 => "杰倫",
    10 => "耕宏",
    11 => "天線",
    12 => "牛角",
    13 => "青蛙",
    14 => "",
    15 => "",
    16 => "",
    17 => "",
    18 => "",
    19 => ""
]);

define("LOWERBODY", [
    0 => "",
    1 => "肌肉",
    2 => "狼形",
    3 => "武士",
    4 => "狂鯊",
    5 => "電子",
    6 => "鉚釘",
    7 => "鬥兔",
    8 => "阿杜",
    9 => "杰倫",
    10 => "耕宏",
    11 => "天線",
    12 => "牛角",
    13 => "青蛙",
    14 => "",
    15 => "",
    16 => "",
    17 => "",
    18 => "",
    19 => ""
]);

define("BASEBODY_EN" , [
    0 => "Copper",
    1 => "Gold",
    2 => "Green",
    3 => "Purple",
    4 => "Leopard",
    5 => "Camo",
    6 => "Red",
    7 => "Silver",
    8 => "Yellow",
    9 => "Black",
    10 => "Blue"
]);

define("HEAD_EN" , [
    0 => "",
    1 => "Sprint fire",
    2 => "Strike lupus",
    3 => "Oni-blade  samurai",
    4 => "Steel biting jaws",
    5 => "Electronic fairy",
    6 => "Violent axe",
    7 => "Bounce ear",
    8 => "Building master",
    9 => "Crazy-Jazz",
    10 => "Graffiti boy",
    11 => "Welding gun",
    12 => "Rattled  buffalo",
    13 => "Frog  eye",
    14 => "",
    15 => "",
    16 => "Hell punk",
    17 => "Rivet attacker",
    18 => "Diving shark",
    19 => ""
]);

define("SHOULDER_EN", [
    0 => "",
    1 => "Sprint fire",
    2 => "Strike lupus",
    3 => "Oni-blade  samurai",
    4 => "Steel biting jaws",
    5 => "Electronic fairy",
    6 => "Violent axe",
    7 => "Bounce ear",
    8 => "Building master",
    9 => "Crazy-Jazz",
    10 => "Graffiti boy",
    11 => "Welding gun",
    12 => "Rattled  buffalo",
    13 => "Frog  eye",
    14 => "PI-Float fighter",
    15 => "Delta agent",
    16 => "",
    17 => "Rivet attacker",
    18 => "",
    19 => "Deepsea explorer"
]);

define("ARMS_EN", [
    0 => "",
    1 => "Sprint fire",
    2 => "Strike lupus",
    3 => "Oni-blade  samurai",
    4 => "Steel biting jaws",
    5 => "Electronic fairy",
    6 => "Violent axe",
    7 => "Bounce ear",
    8 => "Building master",
    9 => "Crazy-Jazz",
    10 => "Graffiti boy",
    11 => "Welding gun",
    12 => "Rattled  buffalo",
    13 => "Frog  eye",
    14 => "",
    15 => "",
    16 => "",
    17 => "",
    18 => "",
    19 => ""
]);

define("LOWERBODY_EN", [
    0 => "",
    1 => "Sprint fire",
    2 => "Strike lupus",
    3 => "Oni-blade  samurai",
    4 => "Steel biting jaws",
    5 => "Electronic fairy",
    6 => "Violent axe",
    7 => "Bounce ear",
    8 => "Building master",
    9 => "Crazy-Jazz",
    10 => "Graffiti boy",
    11 => "Welding gun",
    12 => "Rattled  buffalo",
    13 => "Frog  eye",
    14 => "",
    15 => "",
    16 => "",
    17 => "",
    18 => "",
    19 => ""
]);

